### ISSUE TITLE
extender

### ISSUE THREAD

**Issue by momodding** [GeoSn0w/Yalu-Jailbreak-iOS-10.2#16]
is this support extender tweak?

**Comment by GeoSn0w** [comment]
Yes

**Comment by Jmiah3** [comment]
Love your work & vids Geosn0w....(I'm a sub too) ~ how can I download either your version of Yalu or blueyalu 5 / space yalu from safari??? ~ I am trying to be able to download a version (other then the first basic release of Yalu as that I already have) so that I can import via ipa store. (which I seen somewhere you wrote not to use ipa stores & to avoid at all costs. Howcome?) I am hoping to be able to take advantage of the one (1) year signing period(s) that places like iPA store provide (?) BUT....I would consider YOUR feedback as solid / accurate information so I am hoping you might reply so I can avoid trouble.... ~ Thank you ...Respectfully: Jmiah3
